---
Name: nswdpc-taxonomy-icon
---
SilverStripe\Taxonomy\TaxonomyTerm:
  is_upload: true
  is_css: false
  is_filename: false
  filename_path: 'themes/theme-australiaday/app/static/icons/'
  extensions:
    - 'NSWDPC\Taxonomy\Extensions\TaxonomyIconExtension'
